import assert from 'node:assert/strict';
import {readFile,readdir,stat} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {createHash} from 'node:crypto';
import {articles} from '../content/articles.mjs';
import {categories,services} from '../content/services.mjs';
const root=resolve('dist');
async function walk(dir){return(await Promise.all((await readdir(dir,{withFileTypes:true})).map(e=>e.isDirectory()?walk(dir+'/'+e.name):[dir+'/'+e.name]))).flat();}
const files=await walk(root),html=files.filter(f=>f.endsWith('.html')),titles=new Set(),descriptions=new Set();let linkCount=0,articleWords=[];
assert.equal(articles.length,100);assert.equal(new Set(articles.map(a=>a.slug)).size,100);assert.equal(new Set(articles.map(a=>a.answer)).size,100);assert.equal(new Set(articles.map(a=>a.example)).size,100);assert.equal(categories.length,10);assert.equal(services.length,6);
for(const c of categories)assert.equal(articles.filter(a=>a.category===c.slug).length,10);
async function assertLocal(url,from){if(!url.startsWith('/')&&!url.startsWith('#'))return;const [path,hash]=url.split('#');const target=path?root+decodeURIComponent(path):from;const file=extname(target)?target:target.replace(/\/$/,'')+'/index.html';await stat(file);if(hash){const targetHtml=await readFile(file,'utf8');assert(targetHtml.includes(`id="${hash}"`),`Missing anchor ${url}`);}}
// Control: a missing local target must be rejected, not silently counted as valid.
await assert.rejects(()=>assertLocal('/__missing_verification_control__/',root+'/index.html'));
for(const file of html){const s=await readFile(file,'utf8');assert.equal((s.match(/<h1(?:\s|>)/g)||[]).length,1,file);assert(s.includes('<html lang="fr">'));assert(!/undefined|\[object Object\]|TODO|lorem ipsum/i.test(s),file);const title=s.match(/<title>(.*?)<\/title>/s)?.[1];assert(title&&!titles.has(title),`Duplicate or empty title ${file}`);titles.add(title);const description=s.match(/name="description" content="([^"]+)"/)?.[1];assert(description&&!descriptions.has(description),`Duplicate or empty description ${file}`);descriptions.add(description);assert.match(s,/<link rel="canonical" href="https:\/\/[^" ]+"/);const schemas=[...s.matchAll(/<script type="application\/ld\+json">(.*?)<\/script>/gs)].flatMap(m=>JSON.parse(m[1]));assert(schemas.some(x=>x['@type']==='HomeAndConstructionBusiness'));for(const m of s.matchAll(/(?:href|src)="([^"]+)"/g)){await assertLocal(m[1],file);linkCount++;}for(const m of s.matchAll(/srcset="([^"]+)"/g))for(const item of m[1].split(','))await assertLocal(item.trim().split(' ')[0],file);for(const m of s.matchAll(/<img\b[^>]*>/g)){assert(m[0].includes('alt='),file);assert(m[0].includes('width=')&&m[0].includes('height='),file);}if(schemas.some(x=>x['@type']==='BlogPosting')){const main=s.match(/<article class="prose">(.*?)<\/article>/s)[1];const words=main.replace(/<[^>]*>/g,' ').split(/\s+/).filter(Boolean).length;assert(words>=220,`${file}: short article ${words}`);articleWords.push(words);}}
assert.equal(articleWords.length,100);assert.equal(html.length,127);
const xml=await readFile(root+'/sitemap.xml','utf8'),urls=[...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map(m=>m[1]);assert.equal(urls.length,126);assert.equal(new Set(urls).size,126);for(const url of urls)await assertLocal(new URL(url).pathname,root+'/index.html');
const css=await readFile(root+'/assets/site.css','utf8');assert(!css.includes('@import'));for(const m of css.matchAll(/url\((\/[^)]+)\)/g))await assertLocal(m[1],root+'/index.html');assert(css.includes('prefers-reduced-motion'));assert(css.includes(':focus-visible'));
const imageNames=['ramonage','hero','interieur','maconnerie','patrimoine','toiture','exterieur','matieres','escalier',...categories.map((_,i)=>'category-'+i)];const hashes=[];let imageBytes=0;for(const name of imageNames){const image=await readFile(root+`/assets/${name}-1200.webp`);hashes.push(createHash('sha256').update(image).digest('hex'));imageBytes+=image.length;assert(image.length<400000,`${name} too large`);await stat(root+`/assets/${name}-640.webp`);}assert.equal(new Set(hashes).size,19);await stat(root+'/assets/logo.webp');
console.log(JSON.stringify({pages:html.length,indexablePages:urls.length,articles:articleWords.length,categories:categories.length,articleWords:{min:Math.min(...articleWords),max:Math.max(...articleWords),total:articleWords.reduce((a,b)=>a+b,0)},checkedReferences:linkCount,uniqueEditorialImages:hashes.length,logo:1,desktopEditorialImageBytes:imageBytes}));
console.log('SITE_VERIFIED');
